
#list of subjects that are to be excluded, can be a text file or a list

#exclusionSubjectList: /home2/data/settings/ex_subjects.txt
#exclusionSubjectList: [sub001, sub003]
exclusionSubjectList: None



#list of subjects that are included, can be a text file or a list
#if None, extract data runs on all the subjects

subjectList: /home2/data/Projects/workingMemory/code/CPACAnalysis/configs_3_1_13/subject_list.txt
#subjectList: [sub002, sub003]
#subjectList: None



#Put %s where site and subjects are in the path

#anatomicalTemplate: /home2/data/Incoming/cambridge_fcon/%s/%s/*/mprage_anonymized.nii.gz
anatomicalTemplate: /home2/data/Projects/workingMemory/data/CPAC_analysis/%s/%s/anat_1/mprage.nii.gz 

#Functional Path #Put %s where site and subjects are in the path 

#functionalTemplate: /home2/data/Incoming/cambridge_fcon/%s/%s/*/rest.nii.gz
functionalTemplate: /home2/data/Projects/workingMemory/data/CPAC_analysis/%s/%s/rest_1/rest.nii.gz


#list of sites, can be a text file or a list
#if None, extract data runs on all sites

#siteList: [ABIDE, ADHD-200]
siteList: [wave1]



#Scan Parameters csv file path. This file is mandatory for 
#slice timing correction. please use the right format for the csv, 
#refer to user guide. If None, CPAC does not slice timing correction

#scanParametersCSV: /home2/data/settings/scan_parameters.csv
scanParametersCSV: /home2/data/Projects/workingMemory/code/CPACAnalysis/configs_3_1_13/scan_parameters_multiscan.csv


#output files location
outputSubjectListLocation: /home2/data/Projects/workingMemory/code/CPACAnalysis/configs_3_1_13
